apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app.kubernetes.io/part-of: backend-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: metrics
    prometheus.io/scrape: "true"
spec:
  selector:
    app: backend-deployment
  type:  LoadBalancer
  ports:
    - name: metrics
      protocol: TCP
      port: 5005
      targetPort: 8080

